// ─────────────────────────────────────────────
// Single source of truth for all portfolio data
// ─────────────────────────────────────────────

export const siteConfig = {
  name: "John Lester C. Fuertes",
  shortName: "JL",
  title: "Computer Engineering Graduate",
  tagline:
    "Computer Engineering graduate building web applications and hardware circuits.",
  location: "Taytay, Rizal, Philippines",
  email: "johnlester.fuertes@gmail.com",
  phone: "09774129580",
  university: "Rizal Technological University",
  degree: "BS Computer Engineering",
};

export const navLinks = [
  { label: "Home", href: "/" },
  { label: "Projects", href: "#projects" },
  { label: "Services", href: "#services" },
  { label: "About", href: "#about" },
  { label: "Experience", href: "#experience" },
  { label: "Contact", href: "#contact" },
  { label: "Resume", href: "/resume" },
];

export const socialLinks = [
  { icon: "Github", href: "https://github.com/jlfuertes14", label: "GitHub" },
  { icon: "Linkedin", href: "https://www.linkedin.com/in/jlfuertes14/", label: "LinkedIn" },
  { icon: "Twitter", href: "https://x.com/chiro_yui14", label: "Twitter/X" },
  { icon: "Mail", href: "mailto:johnlester.fuertes@gmail.com", label: "Email" },
  { icon: "Instagram", href: "https://instagram.com/chiro.yui14", label: "Instagram" },
  { icon: "Facebook", href: "https://facebook.com/jl.fuertes14", label: "Facebook" },
  { icon: "Youtube", href: "https://youtube.com/@jl_fuertes14", label: "YouTube" },
];

export const skills = [
  { name: "HTML/CSS/JS", category: "frontend" },
  { name: "React / Next.js", category: "frontend" },
  { name: "TypeScript", category: "frontend" },
  { name: "Tailwind CSS", category: "frontend" },
  { name: "Node.js", category: "backend" },
  { name: "MongoDB", category: "backend" },
  { name: "Python", category: "backend" },
  { name: "C#", category: "backend" },
  { name: "FastAPI", category: "backend" },
  { name: "Flask", category: "backend" },
  { name: "Arduino", category: "hardware" },
  { name: "C++ / Arduino", category: "hardware" },
  { name: "MicroPython", category: "hardware" },
  { name: "ESP32", category: "hardware" },
  { name: "Embedded Systems", category: "hardware" },
  { name: "UI/UX Design", category: "design" },
];

export interface Project {
  title: string;
  category: string;
  description: string;
  techStack: string[];
  imageUrl: string;
  previewImage?: string;
  desktopRightImage?: string;
  desktopLeftImage?: string;
  href: string;
  ctaLabel: string;
  themeColor: string;
  filterCategory?: string;
  isDesktopOnly?: boolean;
}

export const projects: Project[] = [
  {
    title: "CatVision AI",
    category: "AI / MACHINE LEARNING",
    description: "A full-stack Machine Learning application that classifies cat breeds from uploaded images in real-time. Features a custom fine-tuned ResNet-50 Convolutional Neural Network with Grad-CAM explainability deployed behind a FastAPI backend.",
    techStack: ["Next.js", "FastAPI", "Python", "PyTorch", "Docker"],
    imageUrl: "/images/ai_machine_learning/catvision-ai1.png",
    previewImage: "/images/ai_machine_learning/catvision-ai5.png",
    desktopRightImage: "/images/ai_machine_learning/catvision-ai2.png",
    desktopLeftImage: "/images/ai_machine_learning/catvision-ai3.png",
    href: "https://cat-vision-ai-ruby.vercel.app/",
    ctaLabel: "Visit Live Site",
    themeColor: "170 80% 45%",
    filterCategory: "AI/Machine Learning",
    isDesktopOnly: true,
  },
  {
    title: "AniVerse",
    category: "ANIME DISCOVERY ENGINE",
    description: "A fast anime discovery platform featuring real-time streaming, advanced search, and a sleek brutalist-inspired UI.",
    techStack: ["Next.js", "FastAPI", "MongoDB", "Tailwind CSS"],
    imageUrl: "/images/aniverse.png",
    previewImage: "/images/aniverse-mobile-preview.png",
    desktopRightImage: "/images/aniverse-right-image.png",
    href: "https://aniverse-rose.vercel.app/",
    ctaLabel: "Visit Live Site",
    themeColor: "330 80% 55%",
    filterCategory: "Web Development",
  },
  {
    title: "Vitae",
    category: "AI RESUME BUILDER",
    description: "An AI resume builder with ATS scoring, job matching, resume imports, cover letter generation, and a dark control-room interface.",
    techStack: ["Next.js", "Supabase", "Prisma", "Groq + OpenRouter"],
    imageUrl: "/images/vitae.png",
    previewImage: "/images/vitae-mobile-preview.png",
    desktopRightImage: "/images/vitae-right-desktop-view.png",
    desktopLeftImage: "/images/vitae-dashboard.png",
    href: "https://vitae-rho.vercel.app/",
    ctaLabel: "Visit Live Site",
    themeColor: "174 70% 45%",
    filterCategory: "Web Development",
  },
  {
    title: "Onyx",
    category: "AI DESIGN SYSTEM",
    description: "A tool that generates custom design systems for web apps. It turns your vibe prompts into ready-to-use design tokens.",
    techStack: ["Next.js", "Tailwind CSS", "Gemini + Groq", "Framer"],
    imageUrl: "/images/onyx-preview.png",
    previewImage: "/images/onyx-mobile-preview.png",
    desktopRightImage: "/images/onyx-right-dekstop-preveiw.png",
    href: "https://onyx-alpha-murex.vercel.app/",
    ctaLabel: "Visit Live Site",
    themeColor: "262 83% 58%",
    filterCategory: "Web Development",
  },
  {
    title: "Lumina Electronics",
    category: "E-COMMERCE PLATFORM",
    description: "An electronics shop website with real-time inventory tracking and secure checkout.",
    techStack: ["Vite", "Node.js", "MongoDB", "Express"],
    imageUrl: "/images/lumina-preview.png",
    previewImage: "/images/lumina-mobile-preview.png",
    desktopRightImage: "/images/lumina-admin-dashboard.png",
    href: "https://jlfuertes14.github.io/lumina/",
    ctaLabel: "Visit Live Site",
    themeColor: "142 70% 45%",
    filterCategory: "Web Development",
  },
  {
    title: "Chamen Resort",
    category: "HOSPITALITY WEBSITE",
    description: "A resort landing page with smooth animations, a simple booking flow, and a responsive gallery.",
    techStack: ["Next.js", "Framer Motion", "Tailwind CSS", "Lucide"],
    imageUrl: "/images/chamen-resort.png",
    previewImage: "/images/chamen-resort-mobile-preview.png",
    desktopRightImage: "/images/chamen-resort-rght-dekstop.png",
    href: "https://hotel-site-nu.vercel.app/",
    ctaLabel: "Visit Live Site",
    themeColor: "36 80% 50%",
    filterCategory: "Web Development",
  },
  {
    title: "JL Robotics",
    category: "HARDWARE PORTFOLIO",
    description: "A dedicated portfolio website showcasing my hardware and embedded systems projects, including custom circuits, microcontrollers, and robotics.",
    techStack: ["HTML", "CSS", "JavaScript", "ESP32", "C++"],
    imageUrl: "/images/jl-robotics-preview.png",
    previewImage: "/images/jl-robotics-mobile-preview.png",
    desktopRightImage: "/images/jl-robotics-right-desktop-preview.png",
    href: "https://jlfuertes14.github.io/roboportfolio/",
    ctaLabel: "Visit Live Site",
    themeColor: "217 91% 60%",
    filterCategory: "Web Development",
  },
  {
    title: "HatchWatch",
    category: "THESIS",
    description: "An automated smart incubator for duck farming using a Raspberry Pi 5, Arduino, and a YOLOv26 AI model for real-time egg candling and hatch detection.",
    techStack: ["Raspberry Pi 5", "Python", "YOLOv26", "Arduino Uno", "IoT", "Flask"],
    imageUrl: "/images/schoolworks/thesis_defended.png",
    previewImage: "/images/schoolworks/thesis_mobiledashboard.png",
    desktopRightImage: "/images/schoolworks/thesis_project_layout.png",
    desktopLeftImage: "/images/schoolworks/thesis_defended.png",
    href: "https://drive.google.com/file/d/1fj2NnHwaiNY_tbOpURu-jqc7jmcpb642/view?usp=drive_link",
    ctaLabel: "View Thesis Paper",
    themeColor: "40 90% 50%",
    filterCategory: "Schoolworks",
    isDesktopOnly: false,
  },
  {
    title: "Home Automation System",
    category: "SMART HOME IOT",
    description: "A smart home automation system utilizing a Raspberry Pi and Arduino. Features include a touchscreen GUI for controlling appliances and secure RFID/PIN door access.",
    techStack: ["Raspberry Pi", "Python", "Arduino", "C++", "RFID"],
    imageUrl: "/images/schoolworks/home_automation_demo.png",
    previewImage: "/images/schoolworks/home_automation_demo.png",
    desktopRightImage: "/images/schoolworks/home_automation_circuit.png",
    desktopLeftImage: "/images/schoolworks/home_automation.png",
    href: "https://drive.google.com/file/d/1hzY0XQkodVPHMNQCTw7H4zPwbG-4tBwh/view?usp=drive_link",
    ctaLabel: "View Documentation",
    themeColor: "210 80% 55%",
    filterCategory: "Schoolworks",
    isDesktopOnly: true,
  },
  {
    title: "Smart Touchless Trash Bin",
    category: "HARDWARE AUTOMATION",
    description: "An automated 9L trash bin powered by an Arduino, featuring ultrasonic sensors for touchless opening and fill-level monitoring with LCD and RGB LED feedback.",
    techStack: ["Arduino", "C++", "Ultrasonic Sensors", "Servo Motor"],
    imageUrl: "/images/schoolworks/trashcan_demo.png",
    previewImage: "/images/schoolworks/trashcan_portrait.png",
    desktopRightImage: "/images/schoolworks/trashcan_code.png",
    desktopLeftImage: "/images/schoolworks/trashcan_demo.png",
    href: "https://drive.google.com/file/d/1I6LXnemSM_Vtyjxs48YxgkHn8y8_dJXk/view?usp=drive_link",
    ctaLabel: "View Documentation",
    themeColor: "120 70% 45%",
    filterCategory: "Schoolworks",
    isDesktopOnly: false,
  },
  {
    title: "La Vida Pharma",
    category: "PHARMACY MANAGEMENT",
    description: "A comprehensive pharmacy management system and POS built in C#. It features role-based access for Managers and Pharmacists, real-time inventory tracking, prescription management, and PDF report generation.",
    techStack: ["C#", ".NET", "Windows Forms"],
    imageUrl: "/images/schoolworks/lavida_login.png",
    previewImage: "/images/schoolworks/lavida_user_pos.png",
    desktopRightImage: "/images/schoolworks/lavida_manager_dashboard.png",
    desktopLeftImage: "/images/schoolworks/lavida_login.png",
    href: "https://drive.google.com/file/d/16F-MDAPiWvcueB_k1KDwRg6UAu0YpyzC/view?usp=drive_link",
    ctaLabel: "View Documentation",
    themeColor: "160 80% 45%",
    filterCategory: "Schoolworks",
    isDesktopOnly: true,
  },
  {
    title: "Mcdollibee",
    category: "RESTAURANT POS",
    description: "A fast-food restaurant Point of Sale and management system developed in C#, featuring user authentication, an intuitive ordering interface, and an administrative dashboard.",
    techStack: ["C#", ".NET", "Windows Forms"],
    imageUrl: "/images/schoolworks/mcdollibee_login.png",
    previewImage: "/images/schoolworks/mcdollibee_pos.png",
    desktopRightImage: "/images/schoolworks/mcdollibee_dashboard.png",
    desktopLeftImage: "/images/schoolworks/mcdollibee_login.png",
    href: "https://drive.google.com/file/d/1zGezCvsKaL_RXF_dUv3R8gorSohzCPt9/view?usp=drive_link",
    ctaLabel: "View Documentation",
    themeColor: "0 80% 50%",
    filterCategory: "Schoolworks",
    isDesktopOnly: true,
  },
];
